from decouple import config

GITLAB_USERNAME = config('GITLAB_USERNAME')
GITLAB_BASE_URL = config('GITLAB_BASE_URL')
GITLAB_PERSONAL_ACCESS_TOKEN = config('GITLAB_PERSONAL_ACCESS_TOKEN')

JIRA_BASE_URL = config('JIRA_BASE_URL')
JIRA_USERNAME = config('JIRA_USERNAME')
JIRA_PERSONAL_ACCESS_TOKEN = config('JIRA_PERSONAL_ACCESS_TOKEN')

GMAIL_EMAIL = config('GMAIL_EMAIL')
GMAIL_PASSWORD = config('GMAIL_PASSWORD')
GMAIL_NAME = config('GMAIL_NAME')
